name: Deploy to GitHub Releases

on:
  push:
    branches:
      - master

jobs:
  deploy-to-github-releases:
    runs-on: self-hosted
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
     - name: Get Version from Project File
       id: get-version
       shell: bash
       run: echo "version=$(grep -oE '<Version>[^<]+' VelopackPOC/VelopackPOC.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT
     - name: Install .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 8.0.x
     - name: Publish Application
       run: dotnet publish VelopackPOC/VelopackPOC.csproj -c Release -o publish -r win-x64 --self-contained true
     - name: Create Velopack Release
       run: |
          dotnet tool install -g vpk
          vpk download github --repoUrl https://github.com/gulshan-verma/VelopackPOC --token ${{ secrets.VelopackRelease }}
          vpk pack -u VelopackPOC -v ${{ steps.get-version.outputs.version }} -p publish
          vpk upload github --repoUrl https://github.com/gulshan-verma/VelopackPOC --publish --releaseName "VelopackPOC ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }} --token ${{ secrets.VelopackRelease }}
